# Generated by Django 4.2.16 on 2024-09-20 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0010_remove_maintenance_machine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCarriedMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organization', models.CharField(max_length=32, verbose_name='Организация, проводившая ТО')),
            ],
            options={
                'verbose_name': 'Организация, проводившая ТО',
                'verbose_name_plural': 'Организации, проводившие ТО',
            },
        ),
        migrations.CreateModel(
            name='TypeOfMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_maintenance_name', models.CharField(max_length=16, verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Вид ТО',
                'verbose_name_plural': 'Виды ТО',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_maintenance', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.IntegerField(default='', verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(default='', max_length=32, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.machine', verbose_name='Зав. № машины')),
                ('organization_carried_maintenance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maintenance.organizationcarriedmaintenance', verbose_name='Организация, проводившая ТО')),
                ('service_company_maintenance', models.ForeignKey(default=1, limit_choices_to={'groups__name': 'ServiceCompany'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_companies_maintenance', to='service.userdirectory', verbose_name='Сервисная компания')),
                ('type_of_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.typeofmaintenance', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
            },
        ),
    ]
