# Generated by Django 4.2.16 on 2024-09-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcarriedmaintenance',
            name='description_of_organization',
            field=models.CharField(default='', max_length=64, verbose_name='Описание организации'),
        ),
        migrations.AddField(
            model_name='typeofmaintenance',
            name='description_of_type_of_maintenance',
            field=models.CharField(default='', max_length=64, verbose_name='Описание вида ТО'),
        ),
    ]
