# Generated by Django 4.2.16 on 2024-09-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_organizationcarriedmaintenance_description_of_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcarriedmaintenance',
            name='description_of_organization',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='Описание организации'),
        ),
        migrations.AlterField(
            model_name='typeofmaintenance',
            name='description_of_type_of_maintenance',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='Описание вида ТО'),
        ),
    ]
