# Generated by Django 4.2.16 on 2024-09-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_organizationcarriedmaintenance_description_of_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='operating_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Наработка, м/час'),
        ),
    ]
