# Generated by Django 4.2.16 on 2024-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_complaints_downtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='spare_parts_used',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Используемые запасные части'),
        ),
    ]
