# Generated by Django 4.2.16 on 2024-09-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_complaints_spare_parts_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date_of_refusal',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='operating_time_refusal',
            field=models.PositiveIntegerField(verbose_name='Наработка, м/час'),
        ),
    ]
