# Generated by Django 4.2.16 on 2024-09-19 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlled_bridge_model_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_model_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='LeadBridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_bridge_model_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_model_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_model_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_directories', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_factory_number', models.CharField(max_length=16, unique=True)),
                ('engine_factory_number', models.CharField(max_length=16)),
                ('transmission_factory_number', models.CharField(max_length=16)),
                ('lead_bridge_factory_number', models.CharField(max_length=16)),
                ('controlled_bridge_factory_number', models.CharField(max_length=16)),
                ('supply_contract_number_date', models.CharField(max_length=16)),
                ('date_shipment_from_factory', models.DateField()),
                ('consumer', models.CharField(max_length=32)),
                ('delivery_address', models.CharField(max_length=64)),
                ('configuration', models.TextField(max_length=1024)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='service.userdirectory')),
                ('controlled_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.controlledbridgemodel')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.enginemodel')),
                ('lead_bridge_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.leadbridgemodel')),
                ('machine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.machinemodel')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_companies', to='service.userdirectory')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.transmissionmodel')),
            ],
        ),
    ]
