# Generated by Django 4.2.16 on 2024-09-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_machine_client_alter_machine_service_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_maintenance_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='controlledbridgemodel',
            name='controlled_bridge_model_name',
            field=models.CharField(max_length=16, verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='enginemodel',
            name='engine_model_name',
            field=models.CharField(max_length=16, verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='leadbridgemodel',
            name='lead_bridge_model_name',
            field=models.CharField(max_length=16, verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='machine_model_name',
            field=models.CharField(max_length=16, verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='transmissionmodel',
            name='transmission_model_name',
            field=models.CharField(max_length=16, verbose_name='Модель трансмиссии'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_maintenance', models.DateField()),
                ('type_of_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.typeofmaintenance')),
            ],
        ),
    ]
