# Generated by Django 4.2.16 on 2024-09-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_maintenance_operating_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='order_number',
            field=models.CharField(default='', max_length=32, verbose_name='№ заказ-наряда'),
        ),
    ]
