# Generated by Django 4.2.16 on 2024-09-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_methodsofrecovery_nodes_alter_maintenance_machine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodsofrecovery',
            options={'verbose_name': 'Способ восстановления', 'verbose_name_plural': 'Способы восстановления'},
        ),
        migrations.AlterModelOptions(
            name='nodes',
            options={'verbose_name': 'Название Узла', 'verbose_name_plural': 'Название Узлов'},
        ),
    ]
