# Generated by Django 4.2.16 on 2024-09-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_methodsofrecovery_options_alter_nodes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaints',
            options={'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
    ]
