# Generated by Django 4.2.16 on 2024-09-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0012_alter_controlledbridgemodel_description_of_controlled_bridge_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlledbridgemodel',
            name='description_of_controlled_bridge_model',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Описание модели управляемого моста'),
        ),
        migrations.AlterField(
            model_name='enginemodel',
            name='description_of_engine_model',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Описание модели двигателя'),
        ),
        migrations.AlterField(
            model_name='leadbridgemodel',
            name='description_of_lead_bridge_model',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Описание модели ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='description_of_machine_model',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Описание модели техники'),
        ),
        migrations.AlterField(
            model_name='transmissionmodel',
            name='description_of_transmission_model',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Описание модели трансмиссии'),
        ),
        migrations.AlterField(
            model_name='userdirectory',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_directories', to='auth.group', verbose_name='Группы'),
        ),
    ]
