# Generated by Django 4.2.16 on 2024-09-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_controlledbridgemodel_description_of_controlled_bridge_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='supply_contract_number_date',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Договор поставки №, дата'),
        ),
    ]
