# Generated by Django 4.2.16 on 2024-09-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_machine_supply_contract_number_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='supply_contract_number_date',
            field=models.CharField(default=1, max_length=16, verbose_name='Договор поставки №, дата'),
            preserve_default=False,
        ),
    ]
